### ISSUE TITLE
Finalize table structure for the dashboard

### ISSUE THREAD

**Issue by KrishnaRekapalli** [swb-ief/etl-pipeline#14]
* Understand and finalize what format the dashboards need:
    - How many tables table headers and values

**Comment by KrishnaRekapalli** [comment]
@KalyanDUppalapati adding both of us to the issue. And after evening meeting with Bala lets add our comments here and finalize the expected format for dashboard so that the process of ETL and Dashboard building can be de-coupled.

**Comment by KalyanDUppalapati** [comment]
@KrishnaRekapalli , Assuming that the City data structure is fixed, please provide the ward data structure similar to the City.
https://covid19dashbo-s2v2687.slack.com/files/U01BBMK626N/F01BT0HGX6X/image.png
Ward Names should be associated with the City in the same file or else it will be difficult for us to integrate the data & filters in the dashboard.
Thanks.

**Comment by KrishnaRekapalli** [comment]
Closing this as the issue as figured out by the dashboard team
