### ISSUE TITLE
21DMA TPR being set to zero when TPR has 'inf' values

### ISSUE THREAD

**Issue by SangeetaJayadevan** [swb-ief/etl-pipeline#145]
District 21DMA TPR  needs to be zero when underlying values are zero. Currently not computed if values of 'inf' found in TPR. 

> 
> 
> > District 21DMA TPR needs to be zero when underlying values are zero. Currently not computed if values of 'inf' found in TPR.
> 
> @SangeetaJayadevan what is TPR?

Its delta.positivity @talkgarima

**Comment by talkgarima** [comment]
> 
> 
> District 21DMA TPR needs to be zero when underlying values are zero. Currently not computed if values of 'inf' found in TPR.

@SangeetaJayadevan what is TPR?

**Comment by talkgarima** [comment]
Resolved with latest merge
