### ISSUE TITLE
Download PDFs scrapped by the web.archive.org project.

### ISSUE THREAD

**Issue by rscnt** [swb-ief/etl-pipeline#19]
It seems the Wayback machine has scrapped some PDFs for the Mumbai dashboard:

- https://web.archive.org/web/*/http://stopcoronavirus.mcgm.gov.in/assets/docs/Dashboard.pdf

We can collect them and run the scrapping task over them.
We may need to change the page parameters for some.

**Comment by Nozziel** [comment]
pdf scraped was for demonstration purposes so no need to do this anymore
