### ISSUE TITLE
Need to add the html page/pdf file to the Power BI Dashboard.

### ISSUE THREAD

**Issue by KalyanDUppalapati** [swb-ief/etl-pipeline#24]
https://github.com/lijinsgithub/COVID19_India_SWB/blob/master/about_Rt.html
https://github.com/lijinsgithub/COVID19_India_SWB/blob/master/about_Rt.pdf.

**Comment by KalyanDUppalapati** [comment]
@arnimpdm , Please look into the feasibility of embedding the html/pdf page to the power BI dashboard.

**Comment by arnimpdm** [comment]
Hi, Iam on it. We agreed to add a hyperlink to the website onto the dashboard.

**Comment by arnimpdm** [comment]
Done, I added the hyperlink to the dashboard: 
![grafik](https://user-images.githubusercontent.com/37186815/95558639-d7bd5580-0a16-11eb-99cf-e5994f17a671.png)

Please add also the other webpages:
https://raw.githubusercontent.com/lijinsgithub/COVID19_India_SWB/master/eval.html
https://raw.githubusercontent.com/lijinsgithub/COVID19_India_SWB/master/covid19.html
https://raw.githubusercontent.com/lijinsgithub/COVID19_India_SWB/master/about.html
