### ISSUE TITLE
Need to check the data source connectivity from Power BI Service

### ISSUE THREAD

**Issue by KalyanDUppalapati** [swb-ief/etl-pipeline#25]
Please check the data source connectivity from https://app.powerbi.com/groups/me/list/dashboards to the google docs spreadsheets.
https://docs.google.com/spreadsheets/d/1HeTZKEXtSYFDNKmVEcRmF573k2ZraDb6DzgCOSXI0f0/edit#gid=0

**Comment by rscnt** [comment]
@KalyanDUppalapati this is the spreadsheet we would use going foward:

- https://docs.google.com/spreadsheets/d/1j__3SI2j3SSN_lHSPpt4JYVM8FvDpoIwRpMuf1J-Y4k/edit?usp=sharing

The one that is configured to be updated each day in this repo.
