### ISSUE TITLE
Download the R packages to repositories under sub-ief and install them from there

### ISSUE THREAD

**Issue by KrishnaRekapalli** [swb-ief/etl-pipeline#53]
Sometimes the can mirror create issues for downloads. As Salil has mentioned, it may be good idea to keep them in our repos so they can be installed without any issues. This way we control the source

**Comment by svd09** [comment]
Hi,
I have attached the EpiNow2 V 1.1.0 here. While we work  on updating the Rscipt to run with V 1.3.0, we could upload this to the SWB folder and get the yml to load this package from our SWB github account.
I will upload the package to this folder

**Comment by svd09** [comment]
File uploaded. Will close this issue for now.
