### ISSUE TITLE
Update the R_Script to latest calculations

### ISSUE THREAD

**Issue by KrishnaRekapalli** [swb-ief/etl-pipeline#54]
@lijinsgithub has updated R Script located at https://github.com/swb-ief/data-analysis/blob/master/R_pipeline.R

the changes need to be reflected in the

 https://github.com/swb-ief/etl-pipeline/blob/KR-rt-dt-documentation-update/R_scripts/Rt_calcs.R

**Comment by svd09** [comment]
Rscript changes made for epinow2 package version 1.3 and to run with any city

**Comment by Nozziel** [comment]
no longer relevant
