### ISSUE TITLE
R_proc fails to run

### ISSUE THREAD

**Issue by Nozziel** [swb-ief/etl-pipeline#57]
Action R_proc fails with what looks like a missing dependancy

Loading required package: devtools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
Error in install_version("EpiNow2", version = "1.1.0", repos = "http://cran.us.r-project.org") : 
  could not find function "install_version"
Execution halted
Error: Process completed with exit code 1.

**Comment by svd09** [comment]
We have a discussion yesterday evening. We suggested that we could load the packages from our github account rather than depending upon CRAN or remote server. I have uploaded the EpiNow2 version 1.1.0 (that is currently being used) in the etl-pipeline.

**Comment by Nozziel** [comment]
Failed again but with install_version 'missing'

Loading required package: devtools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
Error in install_version("EpiNow2", version = "1.1.0", repos = "http://cran.us.r-project.org") : 
  could not find function "install_version"
Execution halted
Error: Process completed with exit code 1.

**Comment by harrrshitt** [comment]
Looked into the log records and found that the following error is causing a casacading failure - the package 'gert' requires the library libgit2-dev which needs to be specifically installed :

```
----------------------------- ANTICONF -------------------------------
Configuration failed to find libgit2 library. Try installing:
 * brew: libgit2 (MacOS)
 * deb: libgit2-dev (Debian, Ubuntu, etc)
 * rpm: libgit2-devel (Fedora, CentOS, RHEL)
If libgit2 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libgit2.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: git2.h: No such file or directory
compilation terminated.
```

As given in the github page for gert we can try installing libgit2 using this:

```
sudo add-apt-repository ppa:cran/libgit2
sudo apt-get update
sudo apt-get install libgit2-dev
```

**Comment by svd09** [comment]
I have changed the EpiNow2 version (1.3.2) and also the R version (3.6.3). Let us see if that helps

**Comment by Nozziel** [comment]
note there is also a EpiNow2_1.1.0 (1).tar.gz in the root of the repo. notice the (1) in its name.. that's probably not intended.

**Comment by svd09** [comment]
R_proc fails at install_version. have changed the code to install. I hope that this will fix the issue

**Comment by svd09** [comment]
R_proc now runs past Epinow2 and fails at Rscript. Will look into it.

**Comment by Nozziel** [comment]
no longer relevant
