### ISSUE TITLE
Address Ward level data reading issue (g sheet not updating)

### ISSUE THREAD

**Issue by rivera-lanasm** [swb-ief/etl-pipeline#80]
Jan 3, 2020
- spoke with @Nozziel about how to proceed here. Marco suggested to simply replace the methods contained in the Luigi Task in LuigiPipelineSchedule responsible for scraping the ward data from the PDFs with the version he implemented in ward_skeleton branch. 

- I completed the above (see ward_process_update branch) and am testing using the 'test' google sheet, running the relevant parts of the pipeline manually

**Comment by Nozziel** [comment]
no longer relevant
